apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: monitoring
spec:
  secretName: grafana-server-tls
  issuerRef:
    name: cloudflare-clusterissuer # Change if necessary
    kind: ClusterIssuer # Change if necessary
  dnsNames:
    - grafana.k3s.home.vinny.dev.br