---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-nginx
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: demo-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo-nginx

spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: nginx.k3s.seila.vinny.dev.br
    external-dns.alpha.kubernetes.io/target: e30e16e1-9e76-41f4-b97f-a26f0ecb523d.cfargotunnel.com

spec:
 ingressClassName: traefik
 tls:
   - hosts:
       - nginx.k3s.home.vinny.dev.br
     secretName: nginx-certificate-secret
 rules:
   - host: nginx.k3s.home.vinny.dev.br
     http:
       paths:
         - pathType: Prefix
           path: /
           backend:
             service:
               name: nginx-service
               port:
                 number: 80

#apiVersion: traefik.io/v1alpha1
#kind: IngressRoute
#metadata:
#  name: nginx-ingressroute
#  namespace: demo-nginx
#spec:
#  entryPoints:
#    - websecure
#  routes:
#  - match: Host(`nginx.k3s.home.vinny.dev.br`)
#    kind: Rule
#    services:
#    - name: nginx-service
#      port: 80
#  tls:
#    secretName: nginx-certificate-secret
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingressroute-certificate
  namespace: demo-nginx
spec:
  secretName: nginx-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nginx.k3s.home.vinny.dev.br