apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster-pool
  namespace: default
spec:
  addresses:
  - 192.168.100.220-192.168.100.220
---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-homelab
  namespace: default
spec:
  ipAddressPools:
  - cluster-pool
