apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingressroute
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`argocd.k3s.home.vinny.dev.br`)
    kind: Rule
    services:
    - name: argocd-server
      port: http
  tls:
    secretName: argocd-certificate-secret