global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: argocd.k3s.home.vinny.dev.br

  logging:
    # -- Set the global logging format. Either: `text` or `json`
    format: json
    # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
    level: info

fullnameOverride: argocd
configs:
  params:
    server.insecure: false # if using traefik v3 this value should be true