---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---

  # apiVersion: networking.k8s.io/v1
  # kind: Ingress
  # metadata:
  #   name: nginx
  # spec:
  #   ingressClassName: nginx
  #   rules:
  #     - host: nginx.regulus.internal
  #       http:
  #         paths:
  #           - pathType: Prefix
  #             backend:
  #               service:
  #                 name: nginx-service
  #                 port:
  #                   number: 80
  #             path: /
  #   # This section is only required if TLS is to be enabled for the Ingress
  #   # tls:
  #   #   - hosts:
  #   #     - www.example.com
  #   #     secretName: example-tls

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`nginx.k3s.home.vinny.dev.br`)
    kind: Rule
    services:
    - name: nginx-service
      port: 80
  tls:
    secretName: nginx-certificate-secret
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingressroute-certificate
  namespace: default
spec:
  secretName: nginx-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nginx.k3s.home.vinny.dev.br