apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "8.8.2"
    chart: grafana
    helm:
      values: |
         ingress:
            enabled: true
            tls:
              - secretName: grafana-server-tls
              hosts:
                - grafana.k3s.home.vinny.dev.br
            ingressClassName: traefik
            hosts:
              - "grafana.k3s.home.vinny.dev.br"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true