apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: default
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: "0.12.1"
    chart: metallb
    helm:
      values: |
        configInline:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 192.168.100.220-192.168.100.220
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true