apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: "33.2.1"
    chart: traefik
    helm:
      values: |
        ingressRoute:
          dashboard:
              enabled: true
              annotations: 
                external-dns.alpha.kubernetes.io/target: 192.168.100.220
                kubernetes.io/ingress.class: traefik
              entryPoints: ["websecure"]
              matchRule: Host(`batatinha.k3s.home.vinny.dev.br`)
              tls:
                secretName: traefik-dashboard-certificate-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true