apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingressroute-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/depends-on: "traefik"
spec:
  project: default
  source:
    repoURL: https://github.com/Vinny1892/argocd
    path: configure-app/traefik_ingressroute/argocd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
