apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-server-tls
  issuerRef:
    name: cloudflare-clusterissuer # Change if necessary
    kind: ClusterIssuer # Change if necessary
  dnsNames:
    - longhorn.k3s.home.vinny.dev.br