apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.2
      helm:
        values: |
          ingress:
            enabled: true
            ingressClassName: traefik
            tls: true
            tlsSecret: longhorn-server-tls
            pathType: Prefix
            host: longhorn.k3s.home.vinny.dev.br
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system