apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingressroute-certificate
  namespace: default
spec:
  secretName: argocd-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer # Change if necessary
    kind: ClusterIssuer # Change if necessary
  dnsNames:
    - argocd.k3s.home.vinny.dev.br